language: node_js
node_js:
  - "12"
jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=diegobotia -Dsonar.projectKey=laboratorio2 -Dsonar.sources='./app' -X
